<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC6oNaaC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC6oNaaC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC6oNaaC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC6oNaaC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerC6oNaaC\App_KernelDevDebugContainer([
    'container.build_hash' => 'C6oNaaC',
    'container.build_id' => '5cadb1a5',
    'container.build_time' => 1606855595,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC6oNaaC');
